--CONSULTAS SIMPLES
--1. VER TRAMO (I)
--2. VER INFORMACIÓN DE LA TARJETA (T)
--3. VER INFORMACIÓN DE LA CTA DE USUARIO (A)
--4. VER INFORMACIÓN DE LA RESERVA (I)
--5. VER INFORMACIÓN DEL CLIENTE (T)

--CONSULTAS MULTITABLA
--1. VER QUÉ TARJETA TIENE CIERTO USUARIO (A)
--2. VER NOMBRE DE USUARIO Y CLIENTE(S) RELACIONADO(S) (I)
--3. VER LAS ESTACIONES DE CIERTO TRAMO (T)
--4. VER QUÉ LA RESERVA DE CIERTO CLIENTE (A)
--5. VER QUÉ RESERVA CIERTO USUARIO (I)

--CONSULTAS DE RESUMEN
--1. ¿CUÁNTAS RESERVAS SON DE CIERTA FECHA EN CIERTO TRAMO? (T)
--2. ¿CUÁNTOS CLIENTES HAY DE CIERTO PAÍS? (A)
--3. ¿CUÁNTOS CLIENTES HAY DE CIERTA EDAD? (I)
--4. ¿CUÁNTAS PERSONAS SUBEN EN CIERTA ESTACIÓN? (T)
--5. ¿CUÁNTAS PERSONAS BAJAN EN CIERTA ESTACIÓN? (A)